name: Testing using composite

on:
  workflow_dispatch:  

env:
  PARENT_ENV: "i'm your father"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Testing ENVV
        id: envs-composite
        uses: ./actions/envs-sample

      - name: Print envs

        run: |
          echo 'Starting print from parent'
          echo PARENT_ENV=$PARENT_ENV
          echo CHILD_ENV=$CHILD_ENV
          echo CHILD_ENV_SETUP=$CHILD_ENV_SETUP
          echo envs-composite.child-env="${{ steps.envs-composite.outputs.child-env }}"

      - name: Install Python via custom action
        uses: ./actions/setup-python
        with:
          python-version: '3.11'

      - name: Check Python version
        run: python --version

      - name: Run a Python script
        run: |
          echo "print('Hello from Python!')" > hello.py
          python hello.py
  